Update cli and runtime2-todos
apache/daffodil-site pull request #98
Opened 2022-11-12 20:58 UTC by tuxji

Daffodil 3.4.0 has added a new CLI test option and fixed some runtime2 todos, so it's time to update these website pages.

site/cli.md: Add the new CLI test -I daffodilC option.

site/dev/design-notes/runtime2-todos.adoc: Remove todos fixed in 3.4.0 (Improve TDML Runner, C struct/field name collisions, Floating point numbers).  Reorder remaining todos (they were not sorted by any criteria before, now sort by most useful for DFDL developers).

DAFFODIL-2748

2022-11-16 22:40 UTC, mbeckerle requested changes

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +In addition, we should support anonymous/multiple choice groups.
Not so sure. 

I'm perfectly fine with disallowing anonymous choices. 
@stevedlawrence and I were looking at DFDL integration for other systems like Apache Drill, NiFi, Avro, etc. and they generally do not allow anonymous choices. Hence, any DFDL schema that has anonymous choices doesn't integrate well with any of those unless we generate a child element with a generated name, and that makes paths awkward, etc. 

Maybe we just say the Runtime2 DFDL subset doesn't allow anonymous choices?

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +    size_t      _choice_1; // choice of which union field to use
Why are these size_t ? Not at all obvious that a type intended to hold sizes is the right type for these. 

union_tag_t maybe?

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +giving the array's offset and size of all its elements.
by "size of all its elements" you mean in total? or of each of its elements? I think you mean the total size since each child element could be a different size (if they are variable length).

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +but we could save space/memory in childrenERDs
Agreed. We really want arrays to be efficient. No per-element overhead for ERDs. 

This means an "array child" (child within an array) has a distinct representation from an element child. 

Or maybe the general case is arrays, and scalar children are treated as array children with min/maxOccurs 1.

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +and a scalar is just one with 1, 1 as those values,
Ah. Same thought. 

What crosses my mind now, is that all these ERDs, even tough it is one per array, are mostly all statically known in the metadata (ERD) of the enclosing parent element. 

I feel like we should be storing more ERD pointers in parent ERDs and not needing them in instance info in more cases.

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +(means variable-length arrays always have unbounded number of elements).
I'm fine with this restriction as well.

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +which prevent the sbt hanging problem.
Below is discussion of backtracking. I didn't think we were going to allow backtracking or forward speculation. Deterministic subset of DFDL being the target. This means parse errors are fatal. 

Is this something you are thinking we should revisit?

2022-11-16 22:40 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +Perhaps c/daffodil should load such an XML file
Agreed. The choiceDispatchKey should not be evaluated at unparse time. Only at parse time. 

dfdl:outputValueCalc is needed to update elements such that on a re-parse, the choiceDispatchKey value *will be* the right one matching the unparsed choice branch. But that's not automatic. Schema authors must write the dfdl:outputValueCalcs to ensure this.

2022-11-22 15:00 UTC, tuxji reviewed
I've made your suggested clarifications and changes.  Better?

2022-11-22 15:00 UTC, tuxji commented on site/dev/design-notes/runtime2-todos.adoc
> +which prevent the sbt hanging problem.
No, I believe you're right that a deterministic subset of DFDL is still the target for runtime2.  I don't think we are ever going to need backtracking or forward speculation for typical binary network protocols, since these protocols are designed for programs to read them easily.  It seems only certain text and binary file formats will need DFDL's full power (especially text since text can be more ambiguous than binary).

2022-11-22 15:00 UTC, tuxji commented on site/dev/design-notes/runtime2-todos.adoc
> +Perhaps c/daffodil should load such an XML file
I take it that you agree the C unparse code should process an XML infoset without any "no match" errors, even if the choiceDispatchKey is invalid.  I also take it that the C unparse code should not modify the choiceDispatchKey either.  If the schema writer wants to enforce that the choiceDispatchKey is the right one matching the unparsed choice branch, the writer must write the dfdl:outputValueCalc to ensure this.

2022-11-29 16:39 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +but we could save space/memory in childrenERDs
I can't really comment on whether array ERDs help with that. I just think that for this runtime we really do need to make the implementation of arrays very efficient.

2022-11-29 16:43 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +and a scalar is just one with 1, 1 as those values,
Right now, our infoset objects store an ERD pointer in each infoset item. This makes it possible to point at any one item, and interpret it correctly (e.g, convert that one item to XML for visualization/debug) because you can indirect over to the ERD to get all the static info.

But this takes up space, and in most cases, what ERD is needed for a child item is static information of the enclosing parent, so could be information stored only in the parent item's ERD. And inductively then, most infoset items would not have ERDs stored in them, rather the ERD "nest" is all static info. 

That's the idea I was exploring. Can we get rid of infoset items carrying ERD pointers?

2022-11-29 16:47 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +(means variable-length arrays always have unbounded number of elements).
For dfdl:occursCountKind 'expression', should we check min/max occurs? I think that's a question of validation or not. I think data is well-formed for OCK expression no matter what, so I see no reason to enforce min/max occurs.  

I think validation should always be optional. It is valuable to be able to parse sell-formed but invalid data.

2022-11-29 16:48 UTC, mbeckerle commented on site/dev/design-notes/runtime2-todos.adoc
> +Perhaps c/daffodil should load such an XML file
Agree.

2022-11-29 16:49 UTC, mbeckerle approved these changes
+1

2022-11-30 22:37 UTC, tuxji reviewed
Thanks, this helped me improve my thinking about dynamically-sized arrays.  Now will squash and merge.

2022-11-30 22:37 UTC, tuxji commented on site/dev/design-notes/runtime2-todos.adoc
> +but we could save space/memory in childrenERDs
I've revised this section with a better understanding of how to handle dynamically sized arrays with dfdl:occursCountKind = "expression" and dfdl:occursCount = { ../count }.

2022-11-30 22:37 UTC, tuxji commented on site/dev/design-notes/runtime2-todos.adoc
> +and a scalar is just one with 1, 1 as those values,
I understand what you mean better, and I've added a new "Making infosets more efficient" section with the idea you expressed.

2022-11-30 22:37 UTC, tuxji commented on site/dev/design-notes/runtime2-todos.adoc
> +(means variable-length arrays always have unbounded number of elements).
I agree, and I've made the "Arrays" section say the normal case should be no validation since Daffodil must not enforce min/maxOccurs if the user wants to parse and unparse well-formed but invalid data.

2022-11-30 22:42 UTC, merged